apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: haikeuken-cache
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: haikeuken
  labels:
    app: haikeuken
spec:
  replicas: 1
  selector:
    matchLabels:
      app: haikeuken
  template:
    metadata:
      labels:
        app: haikeuken
    spec:
      containers:
      - name: haikeuken
        imagePullPolicy: Always
        image: quay.io/terarocket/haikeuken
        args: ["app"]
        env:
        - name: DATABASE_URL
          value: "postgresql://postgresadmin:admin123@postgres:5432/haikeuken"
        - name: SECRET_KEY_BASE
          value: "radicalrascals"
        ports:
        - containerPort: 3000
        volumeMounts:
        - mountPath: "/opt/app/tmp/cache
          name: haikeuken-cache
      - name: haikeuken-assets
        imagePullPolicy: Always
        image: quay.io/terarocket/haikeuken
        args: ["assets"]
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: haikeuken-service
spec:
  selector:
    app: haikeuken
  ports:
    - name: app
      protocol: TCP
      port: 3000
    - name: assets
      protocol: TCP
      port: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: haikeuken
spec:
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: haikeuken-service
            port:
              number: 3000
      - path: /assets
        pathType: Prefix
        backend:
          service:
            name: haikeuken-service
            port:
              number: 80
---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: haikeuken-recipe-sync
spec:
  schedule: "0 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: haikeuken-recipe-sync
            imagePullPolicy: Always
            image: quay.io/terarocket/haikeuken
            args: ["recipe_sync"]
            volumeMounts:
            - mountPath: "/opt/app/tmp/cache
              name: haikeuken-cache
          restartPolicy: Never
